### ISSUE TITLE
Doc example of pyproject.toml file for adding extras mismatches with behavior of `poetry add <package> -E <extra>`

### ISSUE THREAD

**Issue by esciara** [sdispater/poetry#1339]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

The [`extras` section](https://poetry.eustace.io/docs/pyproject/#extras) in the `pyproject.toml` file's doc page seem incorrect. 

It states:
```toml
[tool.poetry.dependencies]
# These packages are mandatory and form the core of this package’s distribution.
mandatory = "^1.0"

# A list of all of the optional dependencies, some of which are included in the
# below `extras`. They can be opted into by apps.
psycopg2 = { version = "^2.7", optional = true }
mysqlclient = { version = "^1.3", optional = true }

[tool.poetry.extras]
mysql = ["mysqlclient"]
pgsql = ["psycopg2"]
```

But when performing a `poetry add psycopg2 -E pgsql` and `poetry add mysqlclient -E mysql`  to recreate this example, it actually generates the following in the `pyproject.toml` file:

```toml
[tool.poetry.dependencies]
# These packages are mandatory and form the core of this package’s distribution.
mandatory = "^1.0"

# A list of all of the optional dependencies, some of which are included in the
# below `extras`. They can be opted into by apps.
psycopg2 = {version = "^2.7", extras = ["pgsql"]}
mysqlclient = {version = "^1.3", extras = ["mysql"]}

# No [tool.poetry.extras] section
```
If one adds manually the extras as stated in the doc, then `poetry install -E psycopg2` will not work and will throw the message:

```
[ValueError]
Extra [psycopg2] is not specified.
```

Can create a PR for this if the problem is confirmed.
