### ISSUE TITLE
extras installed by default

### ISSUE THREAD

**Issue by esciara** [sdispater/poetry#1340]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option). **N/A**

- **OS version and name**: macos mojave 10.14.6
- **Poetry version**: 0.12.17
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/esciara/aee9b5ed11f9af7b907df9ae6d656caa

### Expected behavior
Following the [`extras` documentation](https://poetry.eustace.io/docs/pyproject/#extras) statement:

> Poetry supports extras to allow expression of:
>
>- optional dependencies, which enhance a package, but are not required; and
>- clusters of optional dependencies.

Extras should not be installed by default when performing a `poetry install`, but should be installable only explicitly through a `poetry install -E <extra>`.

### Actual behavior

Extras added with `poetry add <package> -E <extra>` are installed by default when doing a `poetry install`. 

### Further explanations

Performing a `poetry add behave -E bdd` generates the following in the `pyproject.toml` file adds the following:
```toml
# ~~ snip ~~

[tool.poetry.dependencies]
behave = {version = "^1.2", extras = ["bdd"]}

# ~~ snip ~~
```

The generated line is *without* an `optional = true`, which leads to the package being installed by default with a `poetry install`.

### Workaround
Adding package with `poetry add <package> -E <extra> --optional`.

### Resolution
Change the default behavior of `poetry add <package> -E <extra>` to be equivalent to `poetry add <package> -E <extra> --optional`.

**Comment by esciara** [comment]
Following my comment at https://github.com/sdispater/poetry/issues/1145#issuecomment-526122510 , isn't `poetry add <package> -E <extra>` actually not working properly at all?

Should it not have generated this in `pyproject.toml`:
```toml
# ~~ snip ~~

[tool.poetry.dependencies]
behave = {version = "^1.2", optional = true} 

[tool.poetry.extras]
bdd = ["behave"]

# ~~ snip ~~
```
