### ISSUE TITLE
Support multiple private repositories

### ISSUE THREAD

**Issue by marmida** [sdispater/poetry#14]
pip supports at least two private repositories through the combination of `--index-url` and `--extra-index-url`. It'd be nice to support any number of private repositories, but having at least two is necessary for my particular use case.

PS: thanks for this very promising project!

**Comment by sdispater** [comment]
This is already supported.

You can actually add any number of repositories as described here: https://poetry.eustace.io/docs/repositories/#install-dependencies-from-a-private-repository

When you install packages, poetry will look sequentially in every repository configured.

**Comment by languitar** [comment]
How would that work with the repository specification inside the `pyproject.toml` in `tool.poetry.source`?

**Comment by abn** [comment]
@languitar 

```toml
[[tool.poetry.source]]
name = "foo"
url = "https://foo.bar/simple/"

[[tool.poetry.source]]
name = "bar"
url = "https://bar.baz/simple/"
```

This is equivalent to 
 ```toml
tool.poetry.source = [
  { name = "foo", url = "https://foo.bar/simple/" },
  { name = "bar", url = "https://bar.baz/simple/" }
]
