### ISSUE TITLE
Canonical way for adding development dependencies to "setup.py" file "extras_require".

### ISSUE THREAD

**Issue by KelSolaar** [sdispater/poetry#1416]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Issue

Hi,

I'm looking to move [Colour](https://github.com/colour-science/colour) to Poetry, so far so good except for a minor issue on [Github Actions and Windows](https://github.com/sdispater/poetry/issues/977).

There is however something I might be overlooking but I did not find a good answer for. The context is that issuing `pip install 'colour-science[development]'` will install our [development dependencies](https://github.com/colour-science/colour/blob/develop/setup.py#L53.).

I obviously don't want to lose that capability and the only solution I found is rather unelegant: I need to have our development dependencies listed two times (well, three to be exact):

-  In the `[tool.poetry.dependencies]` section where they are marked as optional, then they can be used in the `[tool.poetry.extras]` section to populate accordingly the `setup.py` file generated with the `poetry build` command.
- In `[tool.poetry.dev-dependencies]` so that `poetry install` installs everything we need for development.

Here is my current *pyproject.toml* file for reference:

```toml
[tool.poetry]
name = "colour"
version = "0.3.13"
description = "Colour Science for Python"
license = "BSD-3-Clause"
authors = [ "Colour Developers" ]
readme = 'README.rst'
repository = "https://github.com/colour-science/colour"
homepage = "https://www.colour-science.org/"
keywords = [
    "color",
    "color-science",
    "color-space",
    "color-spaces",
    "colorspace",
    "colorspaces",
    "colour",
    "colour-science",
    "colour-space",
    "colour-spaces",
    "colourspace",
    "colourspaces",
    "data",
    "dataset",
    "datasets",
    "python",
    "spectral-data",
    "spectral-dataset",
    "spectral-datasets"
]
classifiers=[
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 2.7",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development"
]

[tool.poetry.dependencies]
python = "~2.7 || ^3.5"
imageio = "*"
six = "*"
scipy = "*"

"backports.functools_lru_cache" = { version = "*", optional = true }
biblib-simple = { version = "*", optional = true }
coverage = { version = "*", optional = true }
flake8 = { version = "*", optional = true }
invoke = { version = "*", optional = true }
matplotlib = { version = "*", optional = true }
mock = { version = "*", optional = true }
networkx = { version = "*", optional = true }
nose = { version = "*", optional = true }
numpy = { version = "*", optional = true }
pandas = { version = "*", optional = true }
pygraphviz = { version = "*", optional = true }
restructuredtext-lint = { version = "*", optional = true }
sphinx = { version = "*", optional = true }
sphinx_rtd_theme = { version = "*", optional = true }
sphinxcontrib-bibtex = { version = "*", optional = true }
yapf = { version = "0.23", optional = true }

[tool.poetry.dev-dependencies]
biblib-simple = "*"
coverage = "*"
flake8 = "*"
invoke = "*"
nose = "*"
mock = "*"
restructuredtext-lint = "*"
sphinx = "*"
sphinx_rtd_theme = "*"
sphinxcontrib-bibtex = "*"
yapf = "0.23"

[tool.poetry.extras]
development = [
    "biblib-simple",
    "coverage",
    "flake8",
    "invoke",
    "nose",
    "mock",
    "restructuredtext-lint",
    "sphinx",
    "sphinx_rtd_theme",
    "sphinxcontrib-bibtex",
    "yapf"
]
graphviz = [ "pygraphviz" ]
optional = [ "networkx", "pandas" ]
plotting = [ "backports.functools_lru_cache", "matplotlib" ]
read-the-docs = [ "mock", "numpy", "sphinxcontrib-bibtex"]

[build-system]
requires = [ "poetry>=0.12" ]
build-backend = "poetry.masonry.api"
```

Please let me know if I missed something or if it is a current limitation.

Cheers,

Thomas
