### ISSUE TITLE
Add support for disabling package publish

### ISSUE THREAD

**Issue by iamsauravsharma** [sdispater/poetry#1537]
- [X] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

Currently poetry doesn't support disabling publishing of package to remote repository. Add `publish` key similar to `publish` key present over [cargo manifest](https://doc.rust-lang.org/cargo/reference/manifest.html#the-publish--field-optional) for rust crates. `publish` key can have two types of value either bool or list of repository name. The `publish` field can be used to prevent a package from being published to a remote repository (like PYPI) by mistake, for instance to keep a package private in a company. 
```toml
[tool.poetry]
#....
publish=false
```
```toml
[tool.poetry]
#....
publish=["some-remote-repository-name"]
```

**Comment by 515hikaru** [comment]
I think this proposal is nice.

I set the following for packages that should not be made public.

```toml
[tool.poetry]
exclude = ["**/*"]
```

With this workaround, even if `poetry publish` is executed by mistake, the source code is not published. However, since `poetry build` includes pyproject.toml, setup.py, and PKG-INFO in the tar.gz file, such metadata may be disclosed.

This workaround is not good. I think you need an option to make it impossible to publish.
