### ISSUE TITLE
Issues with repositories after upgrading to 0.10.1

### ISSUE THREAD

**Issue by Tonkonozhenko** [sdispater/poetry#155]
Hi

I have a repository in my config:

```toml
[[tool.poetry.source]]
name = "myrepo"
url = "http://reposerver.local/pypi/packages"
```

In version 0.9.0 everything worked fine, but after upgrade, poetry cannot find correct files. It tries to get file `https://reposerver.local/pypi/packages/helper-0.0.92.tar.gz` instead of 
`https://reposerver.local/pypi/packages/helper/helper-0.0.92.tar.gz` (as was in previous version).
