### ISSUE TITLE
1.0b4 performs unnecessary installs of packages found in a custom repository

### ISSUE THREAD

**Issue by dimbleby** [sdispater/poetry#1562]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Centos 7**: 
- **1.0b4**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/dimbleby/0721a2b8ce3b138e5d4d1f88092113c5 (shows the general shape, I have redacted details of my actual custom repository)

## Issue
If I use a custom repository, as in:

```toml
[[tool.poetry.source]]
name = "custom"
url = "https://example.com/api/pypi/pypi-virtual/simple"
```

then any packages installed from that repository are redundantly re-installed at `poetry update`.

I believe the reason is that:
- the desired package source type is marked as 'legacy' in `poetry.lock`:

```toml
[package.source]
reference = "custom"
type = "legacy"
url = "https://example.com/api/pypi/pypi-virtual/simple"
```
- but the found package source type is left empty, [here](https://github.com/sdispater/poetry/blob/51c7042160a74adf14038460468e5e5a72b0d965/poetry/repositories/installed_repository.py#L25)
- so [this code](https://github.com/sdispater/poetry/blob/51c7042160a74adf14038460468e5e5a72b0d965/poetry/puzzle/solver.py#L92-L93) decides that an update is needed

cf [this comment](https://github.com/sdispater/poetry/pull/1240#discussion_r305579566).  On the plus side, I think that bf2d515a has probably fixed #1240; but it has introduced at least this case where we make unnecessary updates (and maybe others too?).
