### ISSUE TITLE
Suggested workflow for testing a build on a CI service?

### ISSUE THREAD

**Issue by madig** [sdispater/poetry#166]
I want to install a wheel package and have the test suit run over it, like tox does. The purpose is to test that an installed package actually works.

I have a GitLab CI script like this:
```
build:
    stage: build
    script:
        - pip install poetry
        - poetry build
    artifacts:
        name: "${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}"
        paths:
            - dist/*.whl

test:
    stage: test
    script:
        - pip install dist/*.whl pytest ufo2ft
        - cd tests && pytest
```
The test stage receives `dist/*.whl`, which we can install. I have to manually specify the development dependencies though. Doable, but not very elegant. Is there a better workflow with poetry?

**Comment by moigagoo** [comment]
Have you considered using `poetry develop` and then running the tests with `poetry run pytest`?

**Comment by moigagoo** [comment]
Yes it does, but `install` doesn't do that. `install` installs the dependencies, but not the package itself.

**Comment by madig** [comment]
But does it install it in a `-e .` way? Do I test the entire installation procedure with that?

**Comment by moigagoo** [comment]
> But does it install it in a -e . way?
Exactly. See this issue for more information: https://github.com/sdispater/poetry/issues/34

> Do I test the entire installation procedure with that?
You're testing the installed package rather than the installation routine itself with that.

> Maybe call it install-dependencies instead?
Hmmm, maybe `poetry deps` is a good alternative. @sdispater is the one to make this kind of decisions.

**Comment by madig** [comment]
> You're testing the installed package rather than the installation routine itself with that.

Maybe that's good enough. My intention here is to be sure that a package actually installs _and_ works. I got bitten by a Python2/3 Unicode issue in a setup.py once, it worked on Py2 but not on Py3 -- and there was no CI with Py3 set up to catch this before the package hit PyPI.

**Comment by madig** [comment]
I know, we have since improved ;)

**Comment by madig** [comment]
Also, wouldn't this run the tests against the directory instead of the installed package:
```
poetry develop
poetry run pytest
```
?

**Comment by moigagoo** [comment]
I think this will run the tests against the directory, but with the package installed. It's just that in Python's path resolution algorithm current dir comes before other paths, so the package from the current dir will be imported before the one installed with `develop`.

However, should you import the package from a file that doesn't start with `test_`, the version installed with develop will be imported.

But it's the same version anyway, so the result will be the same. `poetry develop` makes the package being tested importable, that's basically all it does.

**Comment by funkyfuture** [comment]
fyi, i currently employ this snippet for the config of Travis CI:

```yaml
install:
  - travis_retry pip install poetry
  - travis_retry poetry install
script:
  - poetry run make $TARGET
```
