### ISSUE TITLE
support namespace packing

### ISSUE THREAD

**Issue by mozartilize** [sdispater/poetry#167]
I follow the docs here: https://packaging.python.org/guides/packaging-namespace-packages/
but it does not work, maybe poetry not support yet?

**Comment by uSpike** [comment]
How would the maintainers feel about an additional optional field in `pyproject.toml` called `module`.  For example:

```
[tool.poetry]
name = "abc-foo"
module = "abc.foo"
...
```
corresponds with a layout like:
```
pyproject.toml
abc/
    foo/
        __init__.py
```

**Comment by RaptDept** [comment]
See https://github.com/sdispater/poetry/issues/356#issuecomment-410193960

**Comment by dfee** [comment]
This isn't an issue for me.

```toml
[tool.poetry]
name = "abc.foo"
version = "2018.0.0"
description = "abc foo module"
authors = ["Devin Fee <dev...>"]
packages = [
    { include = "abc" },
]

[tool.poetry.dependencies]
python = "^3.6.5"
"abc.core" = {path = "../abc.core"}  # other namespaced modules work, too.
```

**Comment by moigagoo** [comment]
@dfee what if the package name is different and doesn't correlate with the dir structure?

**Comment by dfee** [comment]
My directory structure is as follows:
```
repo/
    abc.core/
        pyproject.toml
        abc/
            core/
                __init__.py
    abc.asdf/
        pyproject.toml
        abc/
            asdf/
                __init__.py
    abc.qwerty/
        pyproject.toml
        abc/
            asdf/
                __init__.py
```

That should explain this line `"abc.core" = {path = "../abc.core"}` for everyone else.

@moigagoo is your question about something that looks like the following?
```
repo/  # warning: not my structure
    abc.core/ # same as above
        pyproject.toml
        abc
            core/
                __init__.py
    abc.asdf/ # still just a package root (irrelevant name as I understand it)
        pyproject.toml
        abc.asdf/ # I don't think this complies with PEP420?
            __init__.py
    abc.qwerty/
        pyproject.toml
        my_qwerty/ # I don't think this complies with PEP420?
            __init__.py
```

Yeah, I just don't know that anything besides my *current* structure is compliant with [PEP420](https://www.python.org/dev/peps/pep-0420/)

**Comment by sdispater** [comment]
Poerty support this use case https://packaging.python.org/guides/packaging-namespace-packages/#native-namespace-packages by explicitly declaring the various namespaced packages with the `packages` property.

**Comment by wallrite** [comment]
> This isn't an issue for me.
> 
> ```toml
> [tool.poetry]
> name = "abc.foo"
> version = "2018.0.0"
> description = "abc foo module"
> authors = ["Devin Fee <dev...>"]
> packages = [
>     { include = "abc" },
> ]
> 
> [tool.poetry.dependencies]
> python = "^3.6.5"
> "abc.core" = {path = "../abc.core"}  # other namespaced modules work, too.
> ```

@dfee  Do you have any problems building your project? I have the same structure and faced problem with `poetry build`.

**Comment by pawamoy** [comment]
@maggyero, just to be clear, in

```toml
[tool.poetry]
name = "application_1"
version = "..."
description = "..."
authors = ["..."]
packages = [
  { include = "organization", from = "src" }
]
```

...it is not mandatory to use `application_1` as `name`, right? We could use any name we want, and Poetry will in any case install the `application_1` namespace package in the `organization` one.
