### ISSUE TITLE
Support multiple sources

### ISSUE THREAD

**Issue by MaT1g3R** [sdispater/poetry#209]
poetry only searches one source added in the `tool.poetry.source` section, is there a way to allow adding multiple sources?

**Comment by xsduan** [comment]
This has supposedly been fixed in 0.11.0a1 (#189) although I haven't tested it out myself (and I'm not a developer either so I don't have any info on release schedules).

**Comment by sdispater** [comment]
What do you mean exactly?

You can specify as many sources as you want in the `pyproject.toml` file.

**Comment by BorePlusPlus** [comment]
@MaT1g3R looks like we're on the same path. Once you get past multiple sources issue, you'll hit issue with using repository served on http https://github.com/sdispater/poetry/issues/230

**Comment by angru** [comment]
Is that work or not?

If I put following sources in my pyproject file:
```toml
[tool.poetry.dependencies]
my-package="^0.1.0"

[[tool.poetry.source]]
name = 'my-local-pypi'
url = 'http://localhost/simple/'

[[tool.poetry.source]]
name = 'my-remote-pypi'
url = 'http://remote-pypi.com/simple/'
```
and run `poetry update`, I see only one of these sources in my lock file. But it's important to me to keep both sources in lock file because my-package can be installed from any source depending on current environment. 

I thought I can solve it with `PIP_EXTRA_INDEX_URL="http://localhost/simple/ http://remote-pypi.com/simple/"` and completely remove sources from pyproject file. But in that case I'm not able to install my-package at all.
