### ISSUE TITLE
Add / Install with development is complex / multistep.

### ISSUE THREAD

**Issue by dfee** [sdispater/poetry#371]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

The guide for [path constraints](https://poetry.eustace.io/docs/versions/#path-dependencies) says that to install in "development mode" you should

1) edit the `pyproject.toml` file and add your dependency, then

```toml
[tool.poetry]
name = "mypkg.rpc"
version = "0.1.0"

[tool.poetry.dependencies]
python = "*"
"mypkg.core" = {path = "../mypkg.core"}

[tool.poetry.dev-dependencies]
pytest = "^3.0"
ipython = "^6.5"
```

2) you should `install` with the `--develop` option: `poetry install --develop mykpg.core`.

Naturally, I decided that rather than manually editing the `pyproject.toml` file, I'd use the `add` command. But alas, `add` does not take a `--path` option, and `poetry add --path ../mypkg.core mypkg.core` will go ahead and install it *not in development mode* forcing a second step anyway (as well as additional wasted time due to i/o).

So I think it'd make sense to add `develop` to add and (perhaps) add "development = True" to the TOML dependency config.
