### ISSUE TITLE
ipdb requirement error

### ISSUE THREAD

**Issue by dfee** [sdispater/poetry#376]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS 10.13
- **Poetry version**: 0.11.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/dfee/276c332a2b5352a67abedfdaeba5b48a

## Issue
`ipdb` has an [extras_require](https://github.com/gotcha/ipdb/blob/c69a3d712b275a4d15f6319598732cd278643e09/setup.py#L50):
```python
      extras_require={
          ':python_version == "2.7"': ['ipython >= 5.0.0, < 6.0.0'],
          # No support for python 3.0, 3.1, 3.2.
          ':python_version >= "3.3"': ['ipython >= 5.0.0'],
      },
```

But poetry seems to parse / interpret this erroneously:

```
$ poetry develop
Creating virtualenv demo-py3.6 in /private/tmp/demo/.venv
Updating dependencies
Resolving dependencies... (0.2s)

[SolverProblemError]
Because ipdb (0.11) depends on ipython (>=5.0.0,<6.0.0)
 and demo depends on ipython (6.5), ipdb is forbidden.
So, because demo depends on ipdb (0.11), version solving failed.

develop
```

**Comment by sdispater** [comment]
You project depends on any Python versions so the resolver cannot satisfy everything since you depend explicitely on `ipython=6.5`.

You have to remove `ipython` from you dependencies and let the resolver do the rest.

**Comment by dfee** [comment]
My bad. I updated my `python` dependency to `^3.6` and that solved the problem:
```toml
[tool.poetry]
name = "barry.xyz"
version = "0.1.0"
description = ""
authors = ["Devin Fee <devin@devinfee.com>"]
packages = [
    { include = "barry" },
]

[tool.poetry.dependencies]
python = "^3.6"
"barry.core" = {path = "../barry.core"}
"barry.db" = {path = "../barry.db"}
"barry.rpc" = {path = "../barry.rpc"}

[tool.poetry.dev-dependencies]
pytest = "^3.0"
ipython = "^6.5"
ipdb = "^0.11"

[tool.poetry.plugins."barry.ext"]
"cli:xyz" = "barry.xyz.entrypoints.cli:xyz"
```

Out of curiosity though, how does the dependency algorithm work? One interpretation would be that - even without an explicit python version set - that having:
```toml
ipython = "^6.5"
ipdb = "^0.11"
```

Would be satisfied by a `python = "^3.6"` inherently. That *didn't* match, and it didn't pin my python to a specific version. This is probably the right behavior, but it was a gotcha as my environment was already using `python3.6`.

I actually wonder if it'd be helpful to ask the user to set the python version prior to any install rather than defaulting to '*'...
