### ISSUE TITLE
Maximum Recursion Depth Exceeded on fancyimpute package

### ISSUE THREAD

**Issue by adithyabsk** [sdispater/poetry#394]
OS Version: MacOS 10.13.6 (High Sierra)
Poetry version: Poetry 0.11.4
Python version: 3.6.5 (installed with pyenv)

This might be related to #379 as this package depends on keras 2.0.0 and tensorflow
The verbose output is list below.

Here is minimum replicable pyproject.toml file for the error.

```toml
[tool.poetry]
name = "poetry-demo"
version = "0.1.0"
description = ""
authors = ["Adithya Balaji <todo@todo.com>"]

[tool.poetry.dependencies]
python = "*"
fancyimpute = "0.3.2"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
```

I ran:
```bash
$ poetry install
```

and got 

> Updating dependencies
Resolving dependencies... (2.0s)                   
[RecursionError]     
maximum recursion depth exceeded

[Here is the verbose output (run with -vvv)](https://gist.github.com/adithyabsk/5c5be993dd4b250373c656ee650736a0)
