### ISSUE TITLE
pyproject.toml fields `download_url` and `url`

### ISSUE THREAD

**Issue by sobolevn** [sdispater/poetry#469]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question

It is unclear how `repository` and `documentation` relate to the existing `setuptools` fields like: `download_url` and `url`.

"The pyproject.toml" page does not contain this: https://poetry.eustace.io/docs/pyproject/

My main goal is to make two buttons here: https://pypi.org/project/wemake-python-styleguide/

This setup gives just one link:

```toml
repository = "https://github.com/wemake-services/wemake-python-styleguide"
homepage = "https://wemake-python-styleguide.readthedocs.io"
```

Current attempt:

```toml
repository = "https://github.com/wemake-services/wemake-python-styleguide"
documentation = "https://wemake-python-styleguide.readthedocs.io"
```
