### ISSUE TITLE
Is there a way to depend on local dependencies?

### ISSUE THREAD

**Issue by radix** [sdispater/poetry#47]
If I prefer to include my vendored dependencies directly in my repository, is there a way for me to specify them as a dependency? 

e.g., if I have `vendor/foo`, it seems it'd be nice if I could specify a dependency like

```
[tool.poetry.dependencies]
foo-package = {path = "vendor/foo"}
```

**Comment by sdispater** [comment]
If they are in a distribution format (tarball or wheel), yes you can (since version 0.8.0), like so:

```toml
[tool.poetry.dependencies]
foo-package = { file = "relative/path/to/distribution" }
```
