### ISSUE TITLE
How can I choose a source on a per-dependency basis?

### ISSUE THREAD

**Issue by beaugunderson** [sdispater/poetry#524]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question

I would like to specify a source for a dependency on a per-dependency basis.

I would like to do this for a number of reasons:

- PyPi is much faster than my private repository, so it makes sense to install all of my non-private dependencies from PyPi
- I don't understand the semantics of specifying another source... Will that source be used for all dependencies, or just ones that are not found in PyPi? (If the latter, that is a security issue as someone could register our package's name on PyPi and have their code included in our app)

Therefore it seems to me that the way to have understandable semantics and the best installation speed is to support something like:

```toml
[[tool.poetry.source]]
name = "my-private-repo"
url = "http://<hostname>/simple/"

[tool.poetry.dependencies]
python = "^3.6"
my-private-package = { version = "^x.y.z", source = "my-private-repo }
```
