### ISSUE TITLE
Properly reporting malformed  pyproject.toml file

### ISSUE THREAD

**Issue by vlcinsky** [sdispater/poetry#563]
- **OS version and name**: Debian 9
- **Poetry version**: 0.12.4

Sample (malformed) pyproject.toml file
```toml
[tool.poetry]
name = "parampull"
version = "0.1.0"
description = ""
authors = ["Jan Vlcinsky <jan.vlcinsky@tamtamresearch.com>"]

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.20"
prometheus-client = "^0.4.2"
pyyaml = "^3.13"
attrs = "^18.2"
yarl = "^1.2"
cattrs = "^0.9.0"
click = "^7.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
pdbpp = "^0.9.2"
ipython = "^7.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
parampull = 'parampull:main'
```
## Issue
Running some poetry command with malformed `pyproject.toml` prints messages, which are not very explanatory.

`pyproject.toml` shown above is malformed because sequence of `tool.poetry` sections is interrupted by `build-system` one.
```
$ poetry install
[KeyAlreadyPresent]
Key "poetry" already exists.      

install [--no-dev] [--dry-run] [-E|--extras EXTRAS] [--develop DEVELOP]
```

The message could be more explanatory, if it would mention the toml file is malformed, e,g.:

```
$ poetry install
pyproject.toml file is malformed:
[KeyAlreadyPresent]
Key "poetry" already exists.      

install [--no-dev] [--dry-run] [-E|--extras EXTRAS] [--develop DEVELOP]
```
