### ISSUE TITLE
Poetry run: ModuleOrPackageNotFound with implicit namespace packages (PEP420)

### ISSUE THREAD

**Issue by Kazy** [sdispater/poetry#577]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Arch Linux 4.18.16
- **Poetry version**: 0.12.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/Kazy/692963f6a41c64d38f38ac9a3f95619a

## Issue
I'm using implicit namespace packages to organize the packages at work, which works well by specifying the `packages` value in the `pyproject.toml` like that:
```toml
packages = [
    { include = "org" }
]
```
The file structure is like that:
```
├── org
│   └── subpackage
│       ├── __init__.py
│       └── command
│           └── cli.py
└── pyproject.toml
```

The issue is when you try to do `poetry run my-command`, you get:
```
[ModuleOrPackageNotFound]
No file/folder found for package org-subpackage-command
```

I already found how to fix it and will follow with a PR, but I wanted to create the issue in case my fix isn't the right one, and to make organization easier on your side as well.

**Comment by sdispater** [comment]
In your example `org` is not a package so the error is expected.

**Comment by Kazy** [comment]
That follows the PEP420 way of namespacing packages. If you look at https://packaging.python.org/guides/packaging-namespace-packages/#native-namespace-packages, the `__init__.py` isn't required. Or am I missing something /

**Comment by sdispater** [comment]
You are actually right, sorry. And, yes, your PR should fix this.

**Comment by hroemer** [comment]
This change in poetry 0.12.9 causes my scripts to fail silently, now. Here's a repro:

file structure:

```bash
.
├── pack
│   ├── cli.py
│   └── __init__.py
├── poetry.lock
├── pyproject.toml
└── README.rst
``` 
pyproject.toml:

```toml
[tool.poetry]
name = "pack"
version = "0.1.0"
description = ""
authors = ["me"]

packages = [
    { include="pack", from="." },
]

[tool.poetry.scripts]
my-script = "pack.cli:run"

[tool.poetry.dependencies]
python = "^3.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

run.py:

```python3
def run():
    print("run called")


if __name__ == "__main__":
    run()
```

## poetry==0.12.8

```bash
$> poetry run my-script
run called
```

## poetry==0.12.9

```bash
$> poetry run my-script
```

Any ideas?
