### ISSUE TITLE
Support packages with different folder names

### ISSUE THREAD

**Issue by skorokithakis** [sdispater/poetry#705]
I have a package that I want to call `pysignald` because it is a client for signald, but I want the module to actually be available under `signald`. I called the module `signald` in my package, and called the package itself `pysignald` in the `pyproject.toml`, but poetry refuses to build it because it can't find a package with the same name.

This seems like an unnecessary precaution, no? I would like to name my package something other than what people can use to import it, it seems to me that this use case should be supported.

**Comment by sdispater** [comment]
Isn't the `packages` section what you want: https://poetry.eustace.io/docs/pyproject/#packages

Basically you would have:

```toml
[tool.poetry]
name = "pysignald"
# ...
packages = [
    {include = "signald"}
]
```
