### ISSUE TITLE
Error when trying to add taskw

### ISSUE THREAD

**Issue by pawamoy** [sdispater/poetry#747]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Debian 9 Stretch
- **Poetry version**: 0.12.10
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:

```toml
[tool.poetry]
name = "taskhub"
version = "0.1.0"
description = "Task management tool, supporting import/export from/to different services, with multiple interfaces."
license = "ISC"
authors = ["Timothée Mazzucotelli <pawamoy@pm.me>"]
readme = 'README.md'
repository = "https://github.com/pawamoy/taskhub"
homepage = "https://github.com/pawamoy/taskhub"
keywords = ['tasks', 'tasks-management', 'bugs']
packages = [ { include = "taskhub", from = "src" } ]
include = [
    "README.md",
    "pyproject.toml"
]

[tool.poetry.dependencies]
python = "~3.6"
django = "^2.1"
pygithub = { version = "*", optional = true }

[tool.poetry.extras]
github = ["pygithub"]

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-cov = "*"
pytest-sugar = "*"
ipython = "^7.2"

[tool.poetry.scripts]
taskhub = 'taskhub.cli:main'
```

## Issue
It seems I can't install [`taskw`](https://github.com/ralphbean/taskw) through Poetry.

```console
$ poetry -vvv add taskw --optional
Using virtualenv: /home/pawamoy/Data/isolated/virtualenvs/taskhub-py3.6
                                
[ValueError]     
Unable to parse "ralphbean".  
                                
Exception trace:
 /home/pawamoy/.poetry/lib/poetry/_vendor/py3.6/cleo/application.py in run() at line 94
   status_code = self.do_run(input_, output_)
 /home/pawamoy/.poetry/lib/poetry/console/application.py in do_run() at line 88
   return super(Application, self).do_run(i, o)
 /home/pawamoy/.poetry/lib/poetry/_vendor/py3.6/cleo/application.py in do_run() at line 197
   status_code = command.run(input_, output_)
 /home/pawamoy/.poetry/lib/poetry/console/commands/command.py in run() at line 77
   return super(BaseCommand, self).run(i, o)
 /home/pawamoy/.poetry/lib/poetry/_vendor/py3.6/cleo/commands/base_command.py in run() at line 146
   status_code = self.execute(input_, output_)
 /home/pawamoy/.poetry/lib/poetry/_vendor/py3.6/cleo/commands/command.py in execute() at line 107
   return self.handle()
 /home/pawamoy/.poetry/lib/poetry/console/commands/add.py in handle() at line 69
   packages, allow_prereleases=self.option("allow-prereleases")
 /home/pawamoy/.poetry/lib/poetry/console/commands/init.py in _determine_requirements() at line 230
   requirement["name"], allow_prereleases=allow_prereleases
 /home/pawamoy/.poetry/lib/poetry/console/commands/init.py in _find_best_version_for_package() at line 260
   name, required_version, allow_prereleases=allow_prereleases
 /home/pawamoy/.poetry/lib/poetry/version/version_selector.py in find_best_candidate() at line 29
   package_name, constraint, allow_prereleases=allow_prereleases
 /home/pawamoy/.poetry/lib/poetry/repositories/pool.py in find_packages() at line 65
   name, constraint, extras=extras, allow_prereleases=allow_prereleases
 /home/pawamoy/.poetry/lib/poetry/repositories/pypi_repository.py in find_packages() at line 119
   package = Package(name, version)
 /home/pawamoy/.poetry/lib/poetry/packages/package.py in __init__() at line 40
   self._version = Version.parse(version)
 /home/pawamoy/.poetry/lib/poetry/semver/version.py in parse() at line 200
   raise ValueError('Unable to parse "{}".'.format(text))

add [-D|--dev] [--git GIT] [--path PATH] [-E|--extras EXTRAS] [--optional] [--python PYTHON] [--platform PLATFORM] [--allow-prereleases] [--dry-run] [--] <name> (<name>)...

```
