### ISSUE TITLE
Automatically add extras entry for --optional

### ISSUE THREAD

**Issue by xsduan** [sdispater/poetry#772]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question

So it took a while and 4 tries, but apparently to add extras you have to both do `poetry add lib --optional` *and* add a field in `[tool.poetry.extras]` as a list of dependencies for each group. It would be nice if the default behavior of poetry add lib --optional would either add a field in the extras section automatically or suggest adding a field into extras (like "to add as an extra, add `lib = ["lib"]` to [tool.poetry.extras]" or something), or at a minimum have a section in the docs on how to have "extras".

edit: nvm the extras does describe how to add, but i'd still like to have an cli option to add a new section automatically when `add --optional` (like `add --peer`?)

**Comment by funkyfuture** [comment]
@xsduan that result in something like this, right?

```toml
[tool.poetry.dependencies]
python = ">=3.6"
requests = {version = "^2.21",optional = true}

[tool.poetry.extras]
https-loader = ["requests"]
```
