### ISSUE TITLE
Version mismatch in "build-system.requires" does not brake the build

### ISSUE THREAD

**Issue by sobolevn** [sdispater/poetry#797]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: any
- **Poetry version**: 0.12.11
- pyproject.toml:

```toml
[build-system]
requires = ["poetry==0.12.10"]
build-backend = "poetry.masonry.api"


[tool.poetry]
name = "name"
description = "desc"
version = "0.1.0"
authors = []
```

## Issue

I have specifically specified that my `poetry` version should equal to `0.12.10` in `build-system.requires`.

But, when running commands with `poetry==0.12.11` it does work. I guess, it should *not* work in this case.

### Example

```terminal
» poetry --version
Poetry 0.12.11

» cat pyproject.toml| grep "requires"
requires = ["poetry==0.12.10"]

» poetry lock
Updating dependencies
Resolving dependencies... (4.1s)
...
```

### Expected result

I would expect a message something like: `Failed: Poetry version does not match the one specified in "build-system.requires"`

### Actual result

Working perfectly fine.
