### ISSUE TITLE
Dependency fallback

### ISSUE THREAD

**Issue by jocicmarko** [sdispater/poetry#802]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

Hi, thanks for the awesome work you are doing.
I find myself in a bit of a special situation as I need a fallback of a dependency that failed to install. More specifically, I have a `tensorflow-gpu` dependency which works fine on Linux OS, but is not supported on MacOS. In this case I would need to fallback to `tensorflow` dependency, which has the exactly same API as the `tensorflow-gpu` but different implementation (because of no support for the GPU).
Is it possible to overcome this issue?

Thanks a lot,
Marko

**Comment by jacebrowning** [comment]
I think you should be able to use the `platform` marker:

```toml
tensorflow-gpu = { version = "*", platform = "linux" }
tensorflow = { version = "*", platform = "darwin" }
```
