### ISSUE TITLE
Poetry run command returns not enough values to unpack

### ISSUE THREAD

**Issue by eisque** [sdispater/poetry#850]
I have a script in pyproject.toml
```
[tool.poetry.scripts]
start = "python attribrute/start.py"
```
but when I run poetry run start

```[ValueError]
not enough values to unpack (expected 2, got 1)

run <args> (<args>)...```

OS: ubuntu 18.10

**Comment by jacebrowning** [comment]
Scripts work the same say as [setuptools entry points](https://stackoverflow.com/questions/774824/explain-python-entry-points), so I believe this should be:

```toml
[tool.poetry.scripts]
start = "attribrute.start:__main__"
```

https://poetry.eustace.io/docs/pyproject/#scripts
