### ISSUE TITLE
Resolving dependencies... Cache entry deserialization failed, entry ignored

### ISSUE THREAD

**Issue by tallerasaf** [sdispater/poetry#860]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  MacOS Mojave
- **Poetry version**: 1.0.0a2 

## Issue

Every time I use add, install, update, lock it takes a-lot of time and it also have problem with the cache.

**Comment by zmitchell** [comment]
Could you provide more details? What do you mean that is "has problems with the cache"? Please show us any error messages that you see.

**Comment by Kilo59** [comment]
I'm seeing the same thing, but I'm on Windows10 (`Poetry 0.12.11`).
Apart from the error message it actually seem to be working, as poertry is be correctly resolving the latest version of the package from our private pypi repo.

## `pyproject.toml`
```toml
[tool.poetry]
name = "ct-plugins_template"
version = "0.1.0"
description = ""
authors = ""

[tool.poetry.scripts]
spam  = "eggsample_spam"

[[tool.poetry.source]]
name = "companypypi"
url = "https://company-pypi/simple/"

[tool.poetry.dependencies]
my_package = "*"
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^3.9"
black = {version = "^18.9b0",allows-prereleases = true}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

## Console output

```
>poetry update
Updating dependencies
Resolving dependencies...
Cache entry deserialization failed, entry ignored
Cache entry deserialization failed, entry ignored
Cache entry deserialization failed, entry ignored
Cache entry deserialization failed, entry ignored
Cache entry deserialization failed, entry ignored
Cache entry deserialization failed, entry ignored
Cache entry deserialization failed, entry ignored


Package operations: 0 installs, 3 updates, 0 removals

Writing lock file

 -> 1.12.95) botocore (1.12.94
 -> 1.9.95)g boto3 (1.9.94
 -> 19.2.5)g my_package (19.2.4
```
