### ISSUE TITLE
Include files that are in VCS ignore

### ISSUE THREAD

**Issue by ipmb** [sdispater/poetry#90]
I have a web project that uses Node to compile static assets (CSS & JS). I have the static assets in `.gitignore` so they don't get checked into the repo, but I want them bundled when I create a distribution. It appears that `.gitignore` currently takes precedence over `include` in `pyproject.toml`. Could that be switched?

`.gitignore` has:

```
/myproject/static
```

`pyproject.toml` has:

```toml
[myproject]
include = ["myproject/static/**/*"]
```
