### ISSUE TITLE
`poetry update` removed pytest dependency information in `poetry.lock`

### ISSUE THREAD

**Issue by uSpike** [sdispater/poetry#922]
I am still working on getting a reproducible set of instructions and debug information, but I'd like to get this out there if anyone else has experienced it.

I have a project with `pytest = "^4.0"` as a dev dependency.
I am running `python3.5`.

`pytest` depends on `pathlib2` when python is older than `3.6`.
A recent `poetry update` seems to have deleted the following section from `poetry.lock` section for `pytest`:
```
[package.dependencies.pathlib2]
python = "<3.6"
version = ">=2.2.0"
```
As a result, `pathlib2` is not installed.

**Comment by uSpike** [comment]
Attaching log from `poetry lock -vvvvvvvvvvvvvvvv`
[log2.txt](https://github.com/sdispater/poetry/files/2912458/log2.txt)

**Comment by uSpike** [comment]
I think I've narrowed this down to `pytest` + `pylint` and our internal pypi server.

Here's a script I'm using to test:
```shell
cp pyproject.toml.base pyproject.toml

rm -rf ~/.cache/pip ~/.cache/pypoetry
rm -rf venv
rm -rf poetry.lock
python3.5 -m venv venv
source venv/bin/activate
poetry install -vvv
poetry add -vvv pytest
poetry add -vvv pylint
```
and `pyproject.toml.base` is
```toml
[tool.poetry]
name = "poetry_test"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

#[[tool.poetry.source]]
#name = "xes-pypi"
#url = "https://pypi.xes-mad.com"

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

I am attaching the logs for running the test with the `[[tool.poetry.source]]` section commented ([log_internal_pypi.txt](https://github.com/sdispater/poetry/files/2912713/log_internal_pypi.txt)) and uncommented ([log_external_pypi.txt](https://github.com/sdispater/poetry/files/2912712/log_external_pypi.txt)).

In the end, the issue is that the `internal` case has removes `pathlib2` after `poetry add pylint` is run.  I'm having trouble seeing much else in the logs that would point to why that is happening.

Our internal pypi server is running `pypiserver` and does not host any packages that are also on https://pypi.org
