### ISSUE TITLE
debug:info is sensitive to directory name, not pyproject.toml name

### ISSUE THREAD

**Issue by seansfkelley** [sdispater/poetry#974]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.14.2
- **Poetry version**: 0.12.11
- **~~Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file~~** `pyproject.toml` follows:

```toml
[tool.poetry]
name = "foo"
version = "0.1.0"
description = ""
authors = [""]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

## Issue

This project is named `foo`, and when it's present in a directory named `foo`, `poetry debug:info` prints the following:

```
Poetry
======

 * Version: 0.12.11
 * Python:  3.6.4


Virtualenv
==========

 * Python:         3.6.4
 * Implementation: CPython
 * Path:           /path/to/user/directory/Library/Caches/pypoetry/virtualenvs/foo-py3.6
 * Valid:          True


System
======

 * Platform: darwin
 * OS:       posix
 * Python:   /usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6
```

but if you change the directory name as `mv foo bar`, it loses track of the virtual environment:

```
Poetry
======

 * Version: 0.12.11
 * Python:  3.6.4


Virtualenv
==========

 * Python:         3.6.4
 * Implementation: CPython
 * Path:           NA


System
======

 * Platform: darwin
 * OS:       posix
 * Python:   /usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6
```
