### ISSUE TITLE
Dependency resolution fails for packages that conditionally require minimum sub-dependency versions

### ISSUE THREAD

**Issue by jcastagneri** [sdispater/poetry#997]
## Related Issues
This is similar to #868, but on the other side of the problem.

## Background
`opencv-python`s latest release (4.0.0.21) conditionally requires a minimum `numpy` version of:
1.11.1 if python version < 3.6
1.11.3 if python version >= 3.6
1.14.5 if python version >= 3.7

Poetry will use the greatest lower bound for `numpy` in it's dependency resolution (1.14.5 in this case), regardless of python version. 

## Pyproject.toml
In the following `pyproject.toml`, I've installed `numpy==1.11.3` in a python 3.6 environment, which should be allowed:
```toml
[tool.poetry]
name = "break_poetry"
version = "0.1.0"
description = ""
authors = [""]

[tool.poetry.dependencies]
python = "^3.6"
numpy = "=1.11.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

## Steps to Reproduce
When I run `poetry add opencv-python`, poetry fails with the following:
```bash
> poetry add opencv-python
Using version ^4.0 for opencv-python

Updating dependencies
Resolving dependencies... (0.0s)
                                                                                                                    
[SolverProblemError]                                                                                 
Because no versions of opencv-python match >=4.0,<4.0.0.21 || >4.0.0.21,<5.0                                      
 and opencv-python (4.0.0.21) depends on numpy (>=1.14.5), opencv-python (>=4.0,<5.0) requires numpy (>=1.14.5).  
So, because break-poetry depends on both numpy (=1.11.3) and opencv-python (^4.0), version solving failed.        
```

## Possible Source of the Problem
`opencv-python`s dependencies are conditionally declared in `setup.py` like the following:
```python
    # Only import 3rd-party modules after having installed all the build dependencies:
    # any of them, or their dependencies, can be updated during that process,
    # leading to version conflicts
    minimum_supported_numpy = "1.11.1"

    if sys.version_info[:2] >= (3, 6):
        minimum_supported_numpy = "1.11.3"
    if sys.version_info[:2] >= (3, 7):
        minimum_supported_numpy = "1.14.5"

    numpy_version = get_or_install("numpy", minimum_supported_numpy)
```

## What I Expected
I expect that `opencv-python`s stated dependency requirements are picked up by poetry. In this case, there may not be a way to discover the true `numpy` dependency without running `opencv-python`s `setup.py`.

**Comment by drunkwcodes** [comment]
The format for this in pyproject.toml is described in [here].(https://poetry.eustace.io/docs/versions/#python-restricted-dependencies)

Would you like to post the debug msg here?

**Comment by jcastagneri** [comment]
It still fails even if I explicitly dictate that the package should use a given version for python 3.6:
```toml
[tool.poetry]
name = "break-poetry"
version = "0.1.0"
description = ""
authors = [""]

[tool.poetry.dependencies]
python = "^3.6"
numpy = "1.11.3"
opencv-python = { version = "^4.0", python = "^3.6" }

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

```
Running `poetry lock` against the above `pyproject.toml` fails with exactly the same error as above in the original issue post.

I've already included all of the information from the debug messages, but here it is again:

## Output of `poetry debug:info`
```bash
Poetry
======

 * Version: 0.12.11
 * Python:  3.6.8


Virtualenv
==========

 * Python:         3.6.8
 * Implementation: CPython
 * Path:           $HOME/.cache/pypoetry/virtualenvs/break-poetry-py3.6
 * Valid:          True


System
======

 * Platform: linux
 * OS:       posix
 * Python:   $HOME/.pyenv/versions/3.6.8

```

## Output of `poetry debug:resolve`
```bash
Resolving dependencies... (0.1s)                                                                                                                    
[SolverProblemError]                                                                                 
Because no versions of opencv-python match >=4.0,<4.0.0.21 || >4.0.0.21,<5.0                                      
 and opencv-python (4.0.0.21) depends on numpy (>=1.14.5), opencv-python (>=4.0,<5.0) requires numpy (>=1.14.5).  
So, because break-poetry depends on both numpy (1.11.3) and opencv-python (^4.0), version solving failed.         
                                                                                                                    
debug:resolve [-E|--extras EXTRAS] [--python PYTHON] [--tree] [--install] [--] [<package>]...
```

If possible, it seems to me that `poetry add PACKAGE` should be able to properly register conditional dependencies, and then rectify those against the required versions of python specified in a `pyproject.toml`. In my mind, this is what is failing to happen here.
